In [15]:
import pandas as pd
import numpy as np

%run donnees.ipynb

/tmp/ipykernel_81819/1727889837.py:25: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lieux_23 = pd.read_csv(url_lieux_23, sep=';', encoding='UTF-8')
/tmp/ipykernel_81819/1727889837.py:26: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lieux_22 = pd.read_csv(url_lieux_22, sep=';', encoding='UTF-8')

In [16]:
nouveau_mois = {
    1: "janvier",
    2: "février",
    3: "mars",
    4: "avril",
    5: "mai",
    6: "juin",
    7: "juillet",
    8: "août",
    9: "septembre",
    10: "octobre",
    11: "novembre",
    12: "décembre"
}

nouveau_lum = {
    1:"Plein jour",
    2:"Crépuscule ou aube",
    3:"Nuit sans éclairage public",
    4:"Nuit avec éclairage public non allumé",
    5:"Nuit avec éclairage public allumé"
}

nouveau_int = {
    1:"Hors intersection",
    2:"Intersection en X",
    3:"Intersection en T",
    4:"Intersection en Y",
    5:"Intersection à plus de 4 branches",
    6:"Giratoire",
    7:"Place",
    8:"Passage à niveau",
    9:"Autre intersection"
}

nouveau_atm = {
    -1:"Non renseigné",
    1:"Normale",
    2:"Pluie légère",
    3:"Pluie forte",
    4:"Neige - grêle",
    5:"Brouillard - fumée",
    6:"Vent fort - tempête",
    7:"Temps éblouissant",
    8:"Temps couvert",
    9:"Autre"
}

nouveau_col = {
    -1:"Non renseigné",
    1:"Deux véhicules - frontale",
    2:"Deux véhicules - par l'arrière",
    3:"Deux véhicules - par le côté",
    4:"Trois véhicules - en chaîne",
    5:"Trois véhicules - collisions multiples",
    6:"Autre collision",
    7:"Sans collision"
}

In [17]:
df_caract_24 = df_caract_24.assign(
    mois=df_caract_24.mois.map(nouveau_mois),
    lum=df_caract_24.lum.map(nouveau_lum),
    int=df_caract_24.int.map(nouveau_int),
    atm=df_caract_24.atm.map(nouveau_atm),
    col=df_caract_24.col.map(nouveau_col)
)

df_caract_24["agg"] = np.where(df_caract_24["agg"] == 1, "Hors agglomération", "En agglomération")

df_caract_24

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,mars,2024,07:40,Crépuscule ou aube,70,70285,Hors agglomération,Hors intersection,Brouillard - fumée,Deux véhicules - frontale,D438,"47,56277000","6,75832000"
1,202400000002,20,mars,2024,15:05,Plein jour,21,21054,En agglomération,Intersection en T,Temps éblouissant,Autre collision,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,mars,2024,19:30,Crépuscule ou aube,15,15012,Hors agglomération,Hors intersection,Normale,Autre collision,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,mars,2024,17:50,Plein jour,14,14118,En agglomération,Intersection en T,Temps éblouissant,Deux véhicules - par le côté,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,mars,2024,19:35,Nuit avec éclairage public allumé,13,13106,Hors agglomération,Intersection en T,Pluie légère,Trois véhicules - collisions multiples,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54397,202400054398,10,juillet,2024,02:05,Nuit avec éclairage public allumé,94,94065,En agglomération,Intersection en T,Pluie légère,Autre collision,Avenue Charles Lindbergh,"48,75740000","2,34469000"
54398,202400054399,30,novembre,2024,15:27,Plein jour,92,92062,En agglomération,Hors intersection,Normale,Autre collision,RUE PIERRE GAUDIN,"48,88694322","2,24863619"
54399,202400054400,24,octobre,2024,20:40,Nuit sans éclairage public,29,29068,Hors agglomération,Hors intersection,Normale,Deux véhicules - frontale,PK 031.950 RN12,"48,52619024","-3,96317650"
54400,202400054401,30,novembre,2024,15:40,Plein jour,92,92012,En agglomération,Hors intersection,Normale,Deux véhicules - par le côté,JEAN JAURES (BOULEVARD) 63/215 - 70/208,"48,83286197","2,24394009"
54401,202400054402,10,juillet,2024,08:30,Plein jour,94,94028,En agglomération,Hors intersection,Normale,Trois véhicules - en chaîne,Avenue de la Pompadour,"48,78330000","2,46660000"

In [18]:
df_caract_23 = df_caract_23.assign(
    mois=df_caract_23.mois.map(nouveau_mois),
    lum=df_caract_23.lum.map(nouveau_lum),
    int=df_caract_23.int.map(nouveau_int),
    atm=df_caract_23.atm.map(nouveau_atm),
    col=df_caract_23.col.map(nouveau_col)
)

df_caract_23["agg"] = np.where(df_caract_23["agg"] == 1, "Hors agglomération", "En agglomération")

df_caract_23

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202300000001,7,mai,2023,06:00,Plein jour,75,75101,En agglomération,Intersection en Y,Pluie légère,Sans collision,RUE DE RIVOLI,"48,86638600","2,32347100"
1,202300000002,7,mai,2023,05:30,Nuit avec éclairage public allumé,94,94080,En agglomération,Hors intersection,Pluie forte,Autre collision,Avenue de Paris,"48,84547782","2,42868146"
2,202300000003,7,mai,2023,20:50,Plein jour,94,94022,En agglomération,Intersection en T,Pluie légère,Deux véhicules - frontale,Avenue du Général Leclerc,"48,76240000","2,40655000"
3,202300000004,6,mai,2023,23:57,Nuit avec éclairage public allumé,94,94078,En agglomération,Hors intersection,Pluie forte,Trois véhicules - collisions multiples,Rue de Paris,"48,73248432","2,44687575"
4,202300000005,7,mai,2023,00:50,Nuit avec éclairage public allumé,94,94068,En agglomération,Intersection en X,Pluie forte,Deux véhicules - par le côté,56bis Avenue Raspail,"48,78581000","2,49217000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54817,202300054818,26,octobre,2023,20:45,Nuit avec éclairage public allumé,974,97416,En agglomération,Hors intersection,Normale,Autre collision,LA FONTAINE (RUE JEAN DE),"-21,33828000","55,47771000"
54818,202300054819,26,octobre,2023,19:10,Nuit sans éclairage public,974,97416,Hors agglomération,Hors intersection,Normale,Deux véhicules - par le côté,RN3 (ANCIENNE ROUTE),"-21,28865000","55,50994000"
54819,202300054820,26,octobre,2023,09:40,Plein jour,974,97411,En agglomération,Hors intersection,Normale,Sans collision,BAMBOU (CHEMIN DE LA RUELLE),"-20,90129000","55,40598000"
54820,202300054821,26,octobre,2023,17:20,Plein jour,973,97302,Hors agglomération,Giratoire,Normale,Deux véhicules - par le côté,ROUTE NATIONALE 1,"4,89713000","-52,32854000"
54821,202300054822,20,octobre,2023,16:30,Plein jour,69,69387,En agglomération,Hors intersection,Vent fort - tempête,Deux véhicules - par le côté,Boulevard Yves Farge,"45,73306000","4,82540000"

In [19]:
df_caract_22 = df_caract_22.assign(
    mois=df_caract_22.mois.map(nouveau_mois),
    lum=df_caract_22.lum.map(nouveau_lum),
    int=df_caract_22.int.map(nouveau_int),
    atm=df_caract_22.atm.map(nouveau_atm),
    col=df_caract_22.col.map(nouveau_col)
)

df_caract_22["agg"] = np.where(df_caract_22["agg"] == 1, "Hors agglomération", "En agglomération")

df_caract_22

,Accident_Id,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202200000001,19,octobre,2022,16:15,Plein jour,26,26198,En agglomération,Intersection en T,Normale,Deux véhicules - par le côté,TEIL(vieille route du),"44,5594200000","4,7257200000"
1,202200000002,20,octobre,2022,08:34,Plein jour,25,25204,En agglomération,Intersection en T,Normale,Deux véhicules - par le côté,Miranda,"46,9258100000","6,3462000000"
2,202200000003,20,octobre,2022,17:15,Plein jour,22,22360,En agglomération,Giratoire,Normale,Deux véhicules - par l'arrière,ROND POINT DE BREZILLET,"48,4931620000","-2,7604390000"
3,202200000004,20,octobre,2022,18:00,Plein jour,16,16102,En agglomération,Intersection en T,Temps couvert,Autre collision,LOHMEYER (RUE),"45,6926520000","-0,3262900000"
4,202200000005,19,octobre,2022,11:45,Plein jour,13,13103,Hors agglomération,Hors intersection,Normale,Deux véhicules - par l'arrière,ROUTE DE JEAN MOULIN-RN 538,"43,6755790366","5,0927031775"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55297,202200055298,1,janvier,2022,03:50,Nuit sans éclairage public,2B,2B293,Hors agglomération,Hors intersection,Normale,Autre collision,D71,"42,3101650000","9,4785830000"
55298,202200055299,1,janvier,2022,07:20,Nuit sans éclairage public,84,84074,Hors agglomération,Hors intersection,Normale,Autre collision,D973,"43,7531640000","5,2244760000"
55299,202200055300,1,janvier,2022,04:27,Nuit sans éclairage public,74,74001,Hors agglomération,Hors intersection,Autre,Autre collision,D22,"46,2825320000","6,7328060000"
55300,202200055301,1,janvier,2022,08:40,Plein jour,81,81099,Hors agglomération,Intersection en T,Normale,Deux véhicules - par le côté,Chemin Toulze,"43,9272650000","1,9156370000"
55301,202200055302,1,mars,2022,16:55,Plein jour,41,41018,En agglomération,Hors intersection,Normale,Deux véhicules - par l'arrière,RD956 - Pont Charles De Gaulle,"47,5944040000","1,3533290000"

In [20]:
nouveau_catr = {
    1: "Autoroute",
    2: "Route nationale",
    3: "Route départementale",
    4: "Voie communale",
    5: "Hors réseau public",
    6: "Parc de stationnement ouvert à la circulation publique",
    7: "Route de métropole urbaine",
    9: "Autre"
}

nouveau_circ = {
    -1: "Non renseigné",
    1: "À sens unique",
    2: "Bidirectionnelle",
    3: "À chaussées séparées",
    4: "Avec voies d'affectation variable"
}

nouveau_vosp = {
    -1: "Non renseigné",
    0: "Sans objet",
    1: "Piste cyclable",
    2: "Bande cyclable",
    3: "Voie réservée"
}

nouveau_prof = {
    -1: "Non renseigné",
    1: "Plat",
    2: "Pente",
    3: "Sommet de côte",
    4: "Bas de côte"
}

nouveau_plan = {
    -1: "Non renseigné",
    1: "Partie rectiligne",
    2: "En courbe à gauche",
    3: "En courbe à droite",
    4: "En « S »"
}

nouveau_surf = {
    -1: "Non renseigné",
    1: "Normale",
    2: "Mouillée",
    3: "Flaques",
    4: "Inondée",
    5: "Enneigée",
    6: "Boue",
    7: "Verglacée",
    8: "Corps gras - Huile",
    9: "Autre"
}

nouveau_infra = {
    -1: "Non renseigné",
    0: "Aucun",
    1: "Souterrain - Tunnel",
    2: "Pont - Autopont",
    3: "Bretelle d'échangeur ou de raccordement",
    4: "Voie ferrée",
    5: "Carrefour aménagé",
    6: "Zone piétonne",
    7: "Zone de péage",
    8: "Chantier",
    9: "Autre"
}

nouveau_situ = {
    -1: "Non renseigné",
    0: "Aucun",
    1: "Sur chaussée",
    2: "Sur bande d'arrêt d'urgence",
    3: "Sur accotement",
    4: "Sur trottoir",
    5: "Sur piste cyclable",
    6: "Sur autre voie spéciale",
    8: "Autre"
}

In [21]:
df_lieux_24 = df_lieux_24.assign(
    catr=df_lieux_24.catr.map(nouveau_catr),
    circ=df_lieux_24.circ.map(nouveau_circ),
    vosp=df_lieux_24.vosp.map(nouveau_vosp),
    prof=df_lieux_24.prof.map(nouveau_prof),
    plan=df_lieux_24.plan.map(nouveau_plan),
    surf=df_lieux_24.surf.map(nouveau_surf),
    infra=df_lieux_24.infra.map(nouveau_infra),
    situ=df_lieux_24.situ.map(nouveau_situ)
)

df_lieux_24

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202400000001,Route départementale,D438,0,NaN,Bidirectionnelle,2,Sans objet,Plat,1,260,En courbe à gauche,NaN,7,Normale,Aucun,Sur chaussée,90
1,202400000002,Voie communale,HOTEL DIEU (RUE DE L'),0,NaN,Bidirectionnelle,2,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Autre,Aucun,Sur chaussée,30
2,202400000002,Voie communale,POTERNE (RUE),0,NaN,À sens unique,1,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Autre,Aucun,Sur chaussée,30
3,202400000003,Voie communale,TILLEULS (ALLEE DES),0,NaN,Bidirectionnelle,2,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Normale,Aucun,Sur accotement,50
4,202400000004,Voie communale,AUTHIE (N° 106 PAIRS -115 IMPAIRS),0,NaN,Bidirectionnelle,4,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Normale,Autre,Sur chaussée,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70243,202400054398,Route départementale,NaN,-1,NaN,À sens unique,1,Non renseigné,Plat,-1,-1,Partie rectiligne,NaN,-1,Mouillée,Carrefour aménagé,Sur trottoir,-1
70244,202400054399,Route départementale,RUE PIERRE GAUDIN,0,NaN,À sens unique,1,Bande cyclable,Plat,0,0,En courbe à gauche,NaN,-1,Normale,Aucun,Sur chaussée,30
70245,202400054400,Route nationale,12,0,NaN,À sens unique,2,Sans objet,Pente,31,1 000,Partie rectiligne,NaN,10,Normale,Aucun,Sur chaussée,110
70246,202400054401,Route départementale,JEAN JAURES (BOULEVARD) 63/215 - 70/208,0,NaN,Bidirectionnelle,3,Sans objet,Plat,0,0,Partie rectiligne,NaN,"10,5",Normale,Aucun,Sur chaussée,50
70247,202400054402,Route départementale,86,0,NaN,À sens unique,2,Sans objet,Pente,0,0,Partie rectiligne,NaN,-1,Normale,Pont - Autopont,Sur chaussée,50

In [22]:
df_lieux_23 = df_lieux_23.assign(
    catr=df_lieux_23.catr.map(nouveau_catr),
    circ=df_lieux_23.circ.map(nouveau_circ),
    vosp=df_lieux_23.vosp.map(nouveau_vosp),
    prof=df_lieux_23.prof.map(nouveau_prof),
    plan=df_lieux_23.plan.map(nouveau_plan),
    surf=df_lieux_23.surf.map(nouveau_surf),
    infra=df_lieux_23.infra.map(nouveau_infra),
    situ=df_lieux_23.situ.map(nouveau_situ)
)

df_lieux_23

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202300000001,Voie communale,RUE DE RIVOLI,0,NaN,À sens unique,2,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Mouillée,Aucun,Sur chaussée,30
1,202300000001,Voie communale,RUE SAINT FLORENTIN,0,NaN,À sens unique,1,Sans objet,Plat,-1,-1,Partie rectiligne,NaN,-1,Mouillée,Aucun,Sur chaussée,30
2,202300000002,Route départementale,120,0,NaN,Bidirectionnelle,3,Bande cyclable,Plat,-1,-1,Partie rectiligne,NaN,-1,Mouillée,Aucun,Sur chaussée,50
3,202300000003,Route départementale,5,0,NaN,Bidirectionnelle,4,Sans objet,Plat,1,0,Partie rectiligne,NaN,-1,Mouillée,Carrefour aménagé,Sur chaussée,50
4,202300000003,Route départementale,87,0,NaN,Bidirectionnelle,4,Sans objet,Plat,1,0,Partie rectiligne,NaN,-1,Mouillée,Carrefour aménagé,Sur chaussée,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70855,202300054818,Voie communale,LA FONTAINE (RUE JEAN DE),0,NaN,Bidirectionnelle,2,Sans objet,Plat,-1,0,Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,50
70856,202300054819,Voie communale,RN3 (ANCIENNE ROUTE),0,NaN,Bidirectionnelle,2,Sans objet,Pente,0,0,Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,50
70857,202300054820,Voie communale,BAMBOU (CHEMIN DE LA RUELLE),0,NaN,Bidirectionnelle,2,Sans objet,Pente,0,0,En courbe à gauche,NaN,-1,Normale,Aucun,Autre,30
70858,202300054821,Route nationale,ROUTE NATIONALE 1,0,NaN,Non renseigné,2,Piste cyclable,Plat,4,50,Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,90
70859,202300054822,Voie communale,YVES FARGES (BD),0,NaN,Bidirectionnelle,2,Bande cyclable,Plat,-1,-1,Partie rectiligne,NaN,-1,Normale,Aucun,Sur piste cyclable,30

In [23]:
df_lieux_22 = df_lieux_22.assign(
    catr=df_lieux_22.catr.map(nouveau_catr),
    circ=df_lieux_22.circ.map(nouveau_circ),
    vosp=df_lieux_22.vosp.map(nouveau_vosp),
    prof=df_lieux_22.prof.map(nouveau_prof),
    plan=df_lieux_22.plan.map(nouveau_plan),
    surf=df_lieux_22.surf.map(nouveau_surf),
    infra=df_lieux_22.infra.map(nouveau_infra),
    situ=df_lieux_22.situ.map(nouveau_situ)
)

df_lieux_22

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202200000001,Voie communale,TEIL(vieille route du),0,NaN,Bidirectionnelle,2,Sans objet,Plat,(1),(1),Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,50
1,202200000002,Voie communale,NaN,0,NaN,Bidirectionnelle,2,Sans objet,Plat,(1),(1),Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,50
2,202200000003,Route départementale,ROND POINT DE BREZILLET,0,NaN,Non renseigné,2,Sans objet,Plat,0,0,Partie rectiligne,NaN,-1,Normale,Carrefour aménagé,Sur chaussée,50
3,202200000004,Voie communale,QUATORZE JUILLET (RUE DU),0,NaN,À sens unique,1,Sans objet,Pente,(1),(1),Partie rectiligne,NaN,4,Normale,Aucun,Sur chaussée,30
4,202200000005,Route départementale,ROUTE DE JEAN MOULIN-RN 538,0,NaN,Bidirectionnelle,2,Sans objet,Plat,8,0,Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55297,202200055298,Route départementale,71,-1,NaN,Bidirectionnelle,2,Sans objet,Pente,(1),(1),Partie rectiligne,NaN,-1,Normale,Aucun,Autre,80
55298,202200055299,Route départementale,973,-1,NaN,Bidirectionnelle,2,Sans objet,Plat,29,0,En courbe à gauche,NaN,-1,Normale,Aucun,Sur accotement,80
55299,202200055300,Route départementale,22,0,D,Bidirectionnelle,2,Sans objet,Plat,39,553,En courbe à gauche,NaN,-1,Verglacée,Aucun,Sur accotement,80
55300,202200055301,Route départementale,18,-1,D,Bidirectionnelle,2,Sans objet,Plat,30,125,Partie rectiligne,NaN,-1,Normale,Aucun,Sur chaussée,80
55301,202200055302,Route départementale,NaN,-1,NaN,À chaussées séparées,4,Sans objet,Plat,(1),(1),Partie rectiligne,NaN,4,Normale,Aucun,Sur chaussée,70